# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: MOOGH.MOOGH
PackageVersion: 2026.9.28-1
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://down.aimoogh.com/downloads/win/stable/2026.9.28-1/moogh-win-x64-2026.9.28-1.exe
  InstallerSha256: 73F10D283CAA32C117A0112A72729FFBF2D7B32D055837FC34C5A69D9F2CA2F2
ManifestType: installer
ManifestVersion: 1.10.0
